### ISSUE TITLE
Vue-SSR error

### ISSUE THREAD

**Issue by cafe4it** [Herteby/grapher-vue#1]
Hi, i got an error: 
```
TypeError: query.subscribe is not a function
W20171009-18:24:01.740(7)? (STDERR)     at run (packages/herteby:grapher-vue/grapher-vue.js:88:17)
W20171009-18:24:01.741(7)? (STDERR)     at [object Object]._onTimeout (packages/herteby:grapher-vue/grapher-vue.js:148:10)
W20171009-18:24:01.742(7)? (STDERR)     at Timer.listOnTimeout (timers.js:92:15)

```

**Comment by Herteby** [comment]
Please provide more information.
What does your query look like?
Do you have other queries that work?
So it worked before you added vue-ssr?
I don't use SSR myself, so I don't know if it works or not.

**Comment by cafe4it** [comment]
Thanks.  
May be, grapher-vue cannot run on server.
